name: mol_tree2_lib

on:
  workflow_dispatch:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/mol_tree2_lib.yml'
      - 'tree2/**'
      - 'build/**'
  pull_request:
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - uses: hyoo-ru/mam_build@master2
      with:
        package: mol
        modules: tree2/lib
    
    - uses: JS-DevTools/npm-publish@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        package: ./mol/tree2/lib/-/package.json
