name: mol_time_all

on:
  workflow_dispatch:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/mol_time_all.yml'
      - 'time/**'
      - 'build/**'
  pull_request:
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Build apps
      uses: hyoo-ru/mam_build@master2
      with:
        package: mol
        modules: time/all
    
    - uses: JS-DevTools/npm-publish@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        package: ./mol/time/all/-/package.json
