name: mol_strict

on:
  workflow_dispatch:
  #push:
  #  branches: 
  #    - master
  #  paths:
  #    - '.github/workflows/mol_strict.yml'
  #    - 'strict/**'
  #pull_request:
  #schedule:
  #  - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version:
          - 16
          - 15
          - 14
        
    steps:
    
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build apps
      uses: hyoo-ru/mam_build@master2
      with:
        package: mol
        modules: strict
    
    - uses: JS-DevTools/npm-publish@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        package: ./mol/strict/-/package.json
