name: mol_wire_dom

on:
  workflow_dispatch:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/mol_wire_dom.yml'
      - 'wire/**'
      - 'build/**'
  pull_request:
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0
    
    - name: Build apps
      uses: hyoo-ru/mam_build@master2
      with:
        package: mol
        modules: wire/dom
    
    - uses: JS-DevTools/npm-publish@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        package: ./mol/wire/dom/-/package.json
